---
# Load all component state files into an Ansible map for efficient access
# This allows keeping separate state files while providing map-based access

- name: "State Map - Initialize component states map"
  set_fact:
    component_states_map: {}
    state_files_loaded: 0
    state_files_failed: 0
  tags:
    - state_map
    - state_loading

- name: "State Map - Find all state fact files"
  find:
    paths: "{{ state_directory | default('./state') }}"
    patterns: "state_*.fact"
    recurse: false
  register: state_files_found
  tags:
    - state_map
    - state_loading

- name: "State Map - Display found state files"
  debug:
    msg: "Found {{ state_files_found.files | length }} state files: {{ state_files_found.files | map(attribute='path') | list }}"
  when: 
    - state_files_found.files | length > 0
    - state_map_verbose | default(false)
  tags:
    - state_map
    - state_loading

- name: "State Map - Load each state file and build map entry"
  include_tasks: load_single_state_file.yml
  loop: "{{ state_files_found.files }}"
  loop_control:
    loop_var: item
  tags:
    - state_map
    - state_loading

- name: "State Map - Handle failed state file loads"
  set_fact:
    state_files_failed: "{{ state_files_failed + 1 }}"
  when: false  # Disabled for now since we're using include_tasks
  tags:
    - state_map
    - state_loading

- name: "State Map - Count successful loads"
  set_fact:
    state_files_loaded: "{{ component_states_map.keys() | list | length }}"
  tags:
    - state_map
    - state_loading

- name: "State Map - Display loading summary"
  debug:
    msg: "State map loaded: {{ state_files_loaded }} components"
  tags:
    - state_map
    - state_info

- name: "State Map - Display detailed loading results"
  debug:
    msg:
      - "State Map Loading Complete"
      - "Files loaded: {{ state_files_loaded }}"
      - "Files failed: {{ state_files_failed }}"
      - "Components in map: {{ component_states_map.keys() | list }}"
      - "Map structure: {{ component_states_map | to_nice_yaml }}"
  when: state_map_verbose | default(false)
  tags:
    - state_map
    - state_info

- name: "State Map - Set global state map facts"
  set_fact:
    global_component_states: "{{ component_states_map }}"
    state_map_loaded: true
    state_map_timestamp: "{{ ansible_date_time.iso8601 }}"
  tags:
    - state_map
    - state_loading
