---
# Get components by state
# This task filters components by their current state
# All variables are prefixed with L2_ to avoid namespace conflicts

- name: "L2 Map State - Get components by state"
  set_fact:
    L2_components_by_state: "{{ L2_global_component_states | dict2items | groupby('value.state') }}"
  vars:
    L2_target_state: "{{ L2_state_filter | default('') }}"
  when: 
    - L2_global_component_states is defined
    - L2_state_filter is defined
