---
# Validate state from map
# This task validates that the component state is valid according to the state machine
# All variables are prefixed with L2_ to avoid namespace conflicts

- name: "L2 Map State - Validate state from map"
  assert:
    that:
      - L2_current_state in L2_component_state_machine.states
    fail_msg: "State '{{ L2_current_state }}' is not valid for component '{{ L2_component }}'. Valid states: {{ L2_component_state_machine.states | join(', ') }}"
    success_msg: "State '{{ L2_current_state }}' is valid for component '{{ L2_component }}'"
  when: 
    - L2_current_component_data.state is defined
    - L2_component_state_machine is defined
    - L2_component is defined
