---
# Simple State Change Playbook
# This playbook uses the generic state_change role to change component states
# 
# Usage:
#   ansible-playbook change_component_state.yml -e component=my_component -e transition=RUNNING
#   ansible-playbook change_component_state.yml --tags state_context
#   ansible-playbook change_component_state.yml --tags transition_to_RUNNING

- name: "Change Component State"
  hosts: "{{ target_hosts | default('all') }}"
  gather_facts: true
  become: true
  
  vars:
    component_name: "{{ component | default('resource') }}"
    target_state: "{{ state | default('') }}"
    skip_guard: false

  roles:
    - role: toolchain.fsm.state_change
