---
# Demo playbook for node dependency chain
# This demonstrates the full dependency chain: node1 -> app1 -> os1

- name: "Demo: Node Dependency Chain"
  hosts: localhost
  gather_facts: true

  tasks:
    - name: "Demo 1: Show dependency chain"
      debug:
        msg:
          - "Dependency Chain:"
          - "  node1 depends on: app1"
          - "  app1 depends on: os1"
          - "  os1 has no dependencies"

    - name: "Demo 2: Start os1 first (no dependencies)"
      include_role:
        name: state_change
      vars:
        component_name: "os1"
        target_state: "RUNNING"

    - name: "Demo 3: Start app1 (depends on os1)"
      include_role:
        name: state_change
      vars:
        component_name: "app1"
        target_state: "RUNNING"

    - name: "Demo 4: Start node1 (depends on app1) - will show dependency display"
      include_role:
        name: state_change
      vars:
        component_name: "node1"
        target_state: "RUNNING"

    - name: "Demo 5: Show final states"
      debug:
        msg:
          - "Final component states:"
          - "  os1: {{ ansible_facts.component_state | default('unknown') }}"
          - "  app1: {{ ansible_facts.component_state | default('unknown') }}"
          - "  node1: {{ ansible_facts.component_state | default('unknown') }}"
