---
# Get All Component States using Map-based Approach
# This playbook demonstrates how to get all component states using the Ansible-level map

- name: "Get All Component States using Map"
  hosts: "{{ target_hosts | default('all') }}"
  gather_facts: false
  become: false
  
  tasks:
    - name: "Load state map"
      include_tasks: roles/state_context/tasks/load_state_map.yml
      tags:
        - map_loading

    - name: "List all components by state"
      include_tasks: roles/state_context/tasks/map_state_operations.yml
      vars:
        state_filter: "{{ filter_state | default('') }}"
      when: filter_state is defined and filter_state != ""
      tags:
        - filter_by_state

    - name: "Show all component states"
      include_tasks: roles/state_context/tasks/map_state_operations.yml
      tags:
        - list_all
