---
- name: "Get Component State Output"
  hosts: "localhost"
  gather_facts: true
  
  vars:
    state_display_verbose: true
    
  tasks:
    - name: "Get Node1 State"
      include_role:
        name: state_context
      vars:
        component_name: "node1"
      tags:
        - get_node1_state
        
    - name: "Get App1 State"  
      include_role:
        name: state_context
      vars:
        component_name: "app1"
      tags:
        - get_app1_state
        
    - name: "Display All Component States Summary"
      debug:
        msg:
          - "=== COMPONENT STATE SUMMARY ==="
          - "Node1: {{ component_states.node1.state | default('UNKNOWN') }}"
          - "App1: {{ component_states.app1.state | default('UNKNOWN') }}"
          - "Full State Map:"
          - "{{ component_states | to_nice_json(indent=2) }}"
          - "Retrieved at: {{ ansible_date_time.iso8601 }}"
      tags:
        - state_summary
        
    - name: "Save State to File"
      copy:
        content: |
          Component States as of {{ ansible_date_time.iso8601 }}:
          - Node1: {{ component_states.node1.state | default('UNKNOWN') }}
          - App1: {{ component_states.app1.state | default('UNKNOWN') }}
          
          Full State Map:
          {{ component_states | to_nice_yaml }}
        dest: "{{ playbook_dir }}/component_states.txt"
      tags:
        - save_to_file
