---
# List All Component States using Map-based Approach
# This playbook demonstrates how to list all component states without requiring a specific component

- name: "List All Component States"
  hosts: localhost
  gather_facts: false
  become: false
  
  tasks:
    - name: "Load state map"
      include_tasks: roles/state_context/tasks/load_state_map.yml
      tags:
        - map_loading

    - name: "List all component states"
      include_tasks: roles/state_context/tasks/map_state_operations.yml
      tags:
        - list_all

    - name: "Show components by state"
      include_tasks: roles/state_context/tasks/map_state_operations.yml
      vars:
        state_filter: "{{ filter_state | default('') }}"
      when: filter_state is defined and filter_state != ""
      tags:
        - filter_by_state
