---
# Test playbook for node dependency display
# This demonstrates the node transition with dependency display and pause

- name: "Test Node Dependencies Display"
  hosts: localhost
  gather_facts: true
  vars:
    component_name: "node1"
    target_state: "RUNNING"
    dry_run: false

  tasks:
    - name: "Test: Transition node1 to RUNNING (will show dependencies)"
      include_role:
        name: state_change
      vars:
        component_name: "node1"
        target_state: "RUNNING"

    - name: "Display final state"
      debug:
        msg:
          - "node1 final state: {{ ansible_facts.component_state | default('unknown') }}"
