---
# Test playbook to verify transient state functionality
- name: Test Transient State Functionality
  hosts: localhost
  gather_facts: true
  vars:
    component_name: "node1"
    target_state: "RUNNING"
    dry_run: false
    skip_guard: true
    skip_persist: false
  
  tasks:
    - name: "Test - Display test parameters"
      debug:
        msg:
          - "Testing transient state functionality"
          - "Component: {{ component_name }}"
          - "Target State: {{ target_state }}"
          - "Dry Run: {{ dry_run }}"
    
    - name: "Test - Include state_change role"
      include_role:
        name: state_change
      vars:
        component_name: "{{ component_name }}"
        target_state: "{{ target_state }}"
        dry_run: "{{ dry_run }}"
        skip_guard: "{{ skip_guard }}"
        skip_persist: "{{ skip_persist }}"
