---
# Main tasks for state_context role
# This role reads the current state using map-based approach for efficiency

# Component variable is set by the calling playbook

- name: "State Context - Load component state machine"
  set_fact:
    component_state_machine: "{{ state_machines[asset_definitions[component].state_machine_spec] }}"
  when: 
    - component is defined
    - asset_definitions[component] is defined
    - state_machines is defined
  tags:
    - state_context
    - state_reading
    - state_machine_loading

- name: "State Context - Load state map for efficient access"
  include_tasks: load_state_map.yml
  tags:
    - state_context
    - state_reading
    - map_loading

- name: "State Context - Initialize state reading"
  set_fact:
    current_state: "{{ initial_state }}"
    state_reading_method: "initial"
    state_reading_timestamp: "{{ ansible_date_time.iso8601 }}"
  tags:
    - state_context
    - state_reading

- name: "State Context - Use map-based state access"
  include_tasks: map_state_operations.yml
  when: 
    - global_component_states is defined
    - component is defined
  tags:
    - state_context
    - state_reading
    - map_based

- name: "State Context - Fallback to individual file reading"
  include_tasks: individual_file_reading.yml
  when: 
    - global_component_states is not defined or global_component_states[component] is not defined
    - component is defined
  tags:
    - state_context
    - state_reading
    - fallback

- name: "State Context - Validate read state"
  assert:
    that:
      - current_state in component_state_machine.states
    fail_msg: "State '{{ current_state }}' is not valid for component '{{ component }}'. Valid states: {{ component_state_machine.states | join(', ') }}"
    success_msg: "State '{{ current_state }}' is valid for component '{{ component }}'"
  tags:
    - state_context
    - state_reading

- name: "State Context - Set final state facts"
  set_fact:
    component_state: "{{ current_state }}"
    component_state_timestamp: "{{ state_reading_timestamp }}"
    component_state_method: "{{ state_reading_method }}"
    component_state_valid: true
  tags:
    - state_context
    - state_reading

- name: "State Context - Display current state information"
  debug:
    msg:
      - "Component: {{ component }}"
      - "Current State: {{ current_state }}"
      - "Reading Method: {{ state_reading_method }}"
      - "Reading Timestamp: {{ state_reading_timestamp }}"
      - "State Valid: True"
  when: state_display_verbose | default(true)
  tags:
    - state_context
    - state_info