---
# Custom guard conditions for L2_state_guard role
# This file handles custom validation logic for state transitions

# Custom guard conditions are handled by individual tasks below

- name: "L2 State Guard - Example custom condition - Check system resources"
  assert:
    that:
      - ansible_memtotal_mb > 1024
    fail_msg: "Insufficient memory for transition. Required: 1024MB, Available: {{ ansible_memtotal_mb }}MB"
    success_msg: "System resources are sufficient for transition"
  when: 
    - "'resource_check' in (L2_custom_guard_conditions | default([]))"
    - L2_target_transition in ['STARTING', 'RUNNING']
  tags:
    - L2_state_guard
    - L2_custom_validation

- name: "L2 State Guard - Example custom condition - Check service dependencies"
  systemd:
    name: "{{ item }}"
  register: L2_dependency_service_status
  loop: "{{ L2_component_dependencies | default([]) }}"
  when: 
    - "'dependency_check' in (L2_custom_guard_conditions | default([]))"
    - L2_target_transition in ['STARTING', 'RUNNING']
  tags:
    - L2_state_guard
    - L2_custom_validation

- name: "L2 State Guard - Validate service dependencies"
  assert:
    that:
      - item.status.ActiveState == 'active'
    fail_msg: "Required dependency service '{{ item.item }}' is not active"
    success_msg: "All required dependency services are active"
  loop: "{{ L2_dependency_service_status.results | default([]) }}"
  when: 
    - "'dependency_check' in (L2_custom_guard_conditions | default([]))"
    - L2_target_transition in ['STARTING', 'RUNNING']
    - L2_dependency_service_status.results is defined
  tags:
    - L2_state_guard
    - L2_custom_validation

- name: "L2 State Guard - Example custom condition - Check maintenance window"
  set_fact:
    L2_current_hour: "{{ ansible_date_time.hour | int }}"
    L2_maintenance_window_start: "{{ L2_component_maintenance_window.start | default(2) }}"
    L2_maintenance_window_end: "{{ L2_component_maintenance_window.end | default(4) }}"
  when: 
    - "'maintenance_window_check' in (L2_custom_guard_conditions | default([]))"
    - L2_target_transition in ['MAINTENANCE']
  tags:
    - L2_state_guard
    - L2_custom_validation

- name: "L2 State Guard - Validate maintenance window"
  assert:
    that:
      - L2_current_hour >= L2_maintenance_window_start or L2_current_hour <= L2_maintenance_window_end
    fail_msg: "Maintenance transition not allowed outside maintenance window ({{ L2_maintenance_window_start }}:00 - {{ L2_maintenance_window_end }}:00). Current time: {{ L2_current_hour }}:00"
    success_msg: "Maintenance transition is allowed within maintenance window"
  when: 
    - "'maintenance_window_check' in (L2_custom_guard_conditions | default([]))"
    - L2_target_transition in ['MAINTENANCE']
  tags:
    - L2_state_guard
    - L2_custom_validation
