---
# Main tasks for L2_state_guard role
# This role validates that a state transition is legal according to the state machine

- name: "L2 State Guard - Initialize transition validation for {{ L2_component }}"
  set_fact:
    L2_transition_valid: false
    L2_transition_reason: ""
    L2_guard_timestamp: "{{ ansible_date_time.iso8601 }}"
  tags:
    - L2_state_guard
    - L2_transition_validation

- name: "L2 State Guard - Validate required variables"
  assert:
    that:
      - L2_component is defined and L2_component != ""
      - L2_current_state is defined and L2_current_state != ""
      - L2_target_state is defined and L2_target_state != ""
    fail_msg: "Missing required variables: L2_component='{{ L2_component }}', L2_current_state='{{ L2_current_state }}', L2_target_state='{{ L2_target_state }}'"
    success_msg: "All required variables are present"
  tags:
    - L2_state_guard
    - L2_transition_validation

- name: "L2 State Guard - Check if component exists in state machine"
  assert:
    that:
      - L2_component in asset_definitions
    fail_msg: "Component '{{ L2_component }}' is not defined in state machine. Available components: {{ asset_definitions.keys() | list | join(', ') }}"
    success_msg: "Component '{{ L2_component }}' is defined in state machine"
  tags:
    - L2_state_guard
    - L2_transition_validation

- name: "L2 State Guard - Check if current state is valid"
  assert:
    that:
      - L2_current_state in L2_component_state_machine.states
    fail_msg: "Current state '{{ L2_current_state }}' is not valid for component '{{ L2_component }}'. Valid states: {{ L2_component_state_machine.states | join(', ') }}"
    success_msg: "Current state '{{ L2_current_state }}' is valid for component '{{ L2_component }}'"
  tags:
    - L2_state_guard
    - L2_transition_validation

- name: "L2 State Guard - Check if target transition is valid"
  assert:
    that:
      - L2_target_state in L2_component_state_machine.states
    fail_msg: "Target transition '{{ L2_target_state }}' is not valid for component '{{ L2_component }}'. Valid states: {{ L2_component_state_machine.states | join(', ') }}"
    success_msg: "Target transition '{{ L2_target_state }}' is valid for component '{{ L2_component }}'"
  tags:
    - L2_state_guard
    - L2_transition_validation

- name: "L2 State Guard - Check for self-transition"
  set_fact:
    L2_is_self_transition: "{{ L2_current_state == L2_target_state }}"
  tags:
    - L2_state_guard
    - L2_transition_validation

- name: "L2 State Guard - Check if already in target state"
  set_fact:
    L2_already_in_target_state: "{{ L2_current_state == L2_target_state }}"
  tags:
    - L2_state_guard
    - L2_transition_validation

- name: "L2 State Guard - Validate self-transition"
  assert:
    that:
      - not (L2_is_self_transition and not L2_guard_validation.allow_self_transitions and not L2_already_in_target_state)
    fail_msg: "Self-transition from '{{ L2_current_state }}' to '{{ L2_target_state }}' is not allowed"
    success_msg: "Self-transition validation passed"
  when: L2_is_self_transition
  tags:
    - L2_state_guard
    - L2_transition_validation

- name: "L2 State Guard - Get allowed transitions from current state"
  set_fact:
    L2_allowed_transitions: "{{ L2_component_state_machine.transitions[L2_current_state].to | default([]) }}"
  tags:
    - L2_state_guard
    - L2_transition_validation

- name: "L2 State Guard - Check if current state is transient"
  set_fact:
    L2_current_is_transient: "{{ L2_current_state in ['STARTING', 'STOPPING', 'TERMINATING'] }}"
  tags:
    - L2_state_guard
    - L2_transition_validation

- name: "L2 State Guard - Check if target is a transient state"
  set_fact:
    L2_target_is_transient: "{{ L2_target_state in ['STARTING', 'STOPPING', 'TERMINATING'] }}"
  tags:
    - L2_state_guard
    - L2_transition_validation

- name: "L2 State Guard - Get final state for transient target"
  set_fact:
    L2_final_state_for_transient: "{{ L2_component_state_machine.transient_mappings | dict2items | selectattr('value.transient_state', 'equalto', L2_target_state) | map(attribute='value.success_state') | first | default(L2_target_state) }}"
  when: L2_target_is_transient
  tags:
    - L2_state_guard
    - L2_transition_validation

- name: "L2 State Guard - Set default final state for non-transient target"
  set_fact:
    L2_final_state_for_transient: "{{ L2_target_state }}"
  when: not L2_target_is_transient
  tags:
    - L2_state_guard
    - L2_transition_validation


- name: "L2 State Guard - Check if transition is allowed or from transient state or already in target or to transient state"
  set_fact:
    L2_transition_allowed: "{{ L2_target_state in L2_allowed_transitions or (L2_current_is_transient and L2_target_state in ['RUNNING', 'STOPPED', 'TERMINATED', 'FAILED']) or L2_already_in_target_state or (L2_target_is_transient and L2_final_state_for_transient in L2_allowed_transitions) }}"
  tags:
    - L2_state_guard
    - L2_transition_validation

- name: "L2 State Guard - Validate transition is allowed"
  assert:
    that:
      - L2_transition_allowed
    fail_msg: "Transition from '{{ L2_current_state }}' to '{{ L2_target_state }}' is not allowed. Allowed transitions from '{{ L2_current_state }}': {{ L2_allowed_transitions | join(', ') }}"
    success_msg: "Transition from '{{ L2_current_state }}' to '{{ L2_target_state }}' is allowed"
  tags:
    - L2_state_guard
    - L2_transition_validation

- name: "L2 State Guard - Execute custom guard conditions"
  include_tasks: custom_guard_conditions.yml
  when: L2_custom_guard_conditions | length > 0
  tags:
    - L2_state_guard
    - L2_custom_validation

- name: "L2 State Guard - Validate component dependencies"
  include_tasks: component_dependencies.yml
  when: L2_component_dependencies | default([]) | length > 0
  tags:
    - L2_state_guard
    - L2_dependency_validation

- name: "L2 State Guard - Set transition as valid"
  set_fact:
    L2_transition_valid: true
    L2_transition_reason: "All guard conditions passed"
  tags:
    - L2_state_guard
    - L2_transition_validation

- name: "L2 State Guard - Display transition validation result"
  debug:
    msg:
      - "Component: {{ L2_component }}"
      - "Current State: {{ L2_current_state }}"
      - "Target Transition: {{ L2_target_state }}"
      - "Transition Valid: {{ L2_transition_valid }}"
      - "Validation Reason: {{ L2_transition_reason }}"
      - "Guard Timestamp: {{ L2_guard_timestamp }}"
  tags:
    - L2_state_guard
    - L2_transition_info

- name: "L2 State Guard - Fail if transition is not valid"
  fail:
    msg: "State transition validation failed: {{ L2_transition_reason }}"
  when: not L2_transition_valid
  tags:
    - L2_state_guard
    - L2_transition_validation
