- name: Trivial OS Stop Client
  hosts: localhost
  gather_facts: false

  vars:
    global_asset_name: "app1"

    # vers for toolchain.fsm.state_change
    component_name: "{{ global_asset_name }}"

  tasks:
    - name: First state change to MAINTENANCE
      include_role:
        name: toolchain.fsm.state_change
      vars:
        target_state: "MAINTENANCE"
    
    - name: App Stop
      include_role:
        name: appteam.app1.app_stop
    
    - name: OS Stop  
      include_role:
        name: platformteam.linux.os_stop

    - name: Second state change to STOPPED
      include_role:
        name: toolchain.fsm.state_change
      vars:
        target_state: "STOPPED"    