---
# Main tasks for state_change role
# This role implements state-driven transitions for components using the state machine framework


- name: "State Change: Initialize computed variables with isolation"
  ansible.builtin.set_fact:
    component: "{{ component_name }}"
    asset_type: "{{ asset_definitions[component_name].asset_type | default('app') }}"
    component_services: "{{ asset_definitions[component_name].services | default([]) }}"
    component_processes: "{{ asset_definitions[component_name].processes | default([]) }}"
    component_ports: "{{ asset_definitions[component_name].ports | default([]) }}"
    component_dependencies: "{{ asset_definitions[component_name].dependencies | default([]) }}"
    component_maintenance_window: "{{ asset_definitions[component_name].maintenance_window | default({}) }}"
    component_state_machine_spec: "{{ asset_definitions[component_name].state_machine_spec | default('app_lifecycle') }}"
    actual_target_state: "{{ target_state }}"
  tags:
    - always
    - variable_isolation

- name: "State Change: Initialize state machine variables with isolation"
  ansible.builtin.set_fact:
    state_machine_config: "{{ state_machine | combine({'fact_file_path': './state/state_' + component + '.fact'}) }}"
    component_state_machine: "{{ state_machines[component_state_machine_spec] }}"
    asset_type_info: "{{ asset_types[asset_type] | default({}) }}"
    transition_role_name: "{{ asset_types[asset_type].role_name | default('transition_' + asset_type) }}"
    transition_role_collection: "{{ asset_types[asset_type].role_collection | default('') }}"
    transition_role_timeout: "{{ asset_types[asset_type].default_timeout | default(300) }}"
  tags:
    - always
    - variable_isolation

- name: "State Change: Build full role name with isolation"
  ansible.builtin.set_fact:
    transition_role_full_name: "{{ (transition_role_collection + '.' + transition_role_name) if transition_role_collection != '' else transition_role_name }}"
  tags:
    - always
    - variable_isolation

- name: "State Change: Pre-Task - Validate component type configuration"
  assert:
    that:
      - asset_type in asset_types
    fail_msg: "Asset type '{{ asset_type }}' is not defined in asset_types configuration. Available types: {{ asset_types.keys() | list | join(', ') }}"
    success_msg: "Asset type '{{ asset_type }}' is valid"
  when: asset_type_config.validate_role_existence | default(true)

- name: "State Change: Pre-Task - Validate role existence"
  assert:
    that:
      - transition_role_name is defined
      - transition_role_name != ""
    fail_msg: "Failed to resolve role name for asset type '{{ asset_type }}'"
    success_msg: "Resolved role '{{ transition_role_name }}' for asset type '{{ asset_type }}'"

- name: "State Change: Pre-Task - Validate required variables"
  ansible.builtin.assert:
    that:
      - component_name is defined and component_name != ""
      - component_name in asset_definitions
    fail_msg: "Invalid component '{{ component_name }}'. Available components: {{ asset_definitions.keys() | list | join(', ') }}"
    success_msg: "Component '{{ component_name }}' is valid"

- name: "State Change: Pre-Task - Validate state if provided"
  ansible.builtin.assert:
    that:
      - target_state == "" or target_state in component_state_machine.states
    fail_msg: >-
      Invalid state '{{ target_state }}' for component '{{ component_name }}'.
      Valid states: {{ component_state_machine.states | join(', ') }}
    success_msg: "State '{{ target_state }}' is valid for component '{{ component_name }}'"
  when: target_state != ""

- name: "State Change: Pre-Task - Display execution parameters"
  ansible.builtin.debug:
    msg:
      - "Component: {{ component_name }}"
      - "Target Hosts: {{ target_hosts | default('all') }}"
      - "Target State: {{ target_state | default('none') }}"
      - "Skip Guard: {{ skip_guard }}"
      - "Skip Persist: {{ skip_persist }}"
      - "Dry Run: {{ dry_run }}"

# State Context - Read current state
- name: "State Change: State Context - Read current state"
  ansible.builtin.include_role:
    name: state_context
  vars:
    component: "{{ component_name }}"
    asset_type: "{{ asset_type }}"
  tags:
    - state_context
    - state_reading
    - "state_reading_{{ component_name }}"

# State Change: Set component state in global map (moved to end of role)

# State Transient - Handle automatic transient state mapping
- name: "State Change: Set variables for state_transient with isolation"
  ansible.builtin.set_fact:
    component: "{{ component_name }}"
    target_state: "{{ target_state }}"
    current_state: "{{ component_state }}"
    actual_target_state: "{{ target_state }}"
    original_target_state: "{{ target_state }}"
  tags:
    - always
    - variable_isolation

- name: "State Change: State Transient - Handle transient state mapping"
  ansible.builtin.include_role:
    name: state_transient
  vars:
    component: "{{ component_name }}"
    target_state: "{{ actual_target_state }}"
    current_state: "{{ component_state }}"
  tags:
    - state_transient
    - transient_handling

- name: "State Change: Capture transient state results"
  ansible.builtin.set_fact:
    actual_target_state: "{{ actual_target_state | default(actual_target_state) }}"
    transient_state: "{{ transient_state | default('') }}"
    transient_success_state: "{{ transient_success_state | default('') }}"
    transient_failure_state: "{{ transient_failure_state | default('') }}"
    transient_timeout: "{{ transient_timeout | default(300) }}"
    skip_transient_mapping: "{{ skip_transient_mapping | default(false) }}"
  tags:
    - state_transient
    - transient_handling

# State Guard - Validate transition (if transition is specified)
- name: "State Change: State Guard - Skip guard validation"
  ansible.builtin.debug:
    msg: "State guard validation skipped for {{ component_name }} (skip_guard=true)"
  when: 
    - target_state is defined
    - target_state != ""
    - component_state is defined
    - skip_guard | default(false)

# PRE State Guard - Basic transition validation before asset transition
- name: "State Change: PRE State Guard - Skip PRE guard validation for configured asset types"
  ansible.builtin.debug:
    msg: "PRE State guard validation skipped for {{ component_name }} (asset_type={{ asset_type }}, disable_pre_state_guard=true)"
  when: 
    - target_state is defined
    - target_state != ""
    - component_state is defined
    - asset_type_info.disable_pre_state_guard | default(false)
  tags:
    - pre_state_guard
    - transition_validation

- name: "State Change: PRE State Guard - Validate basic transition"
  ansible.builtin.include_tasks: "{{ playbook_dir }}/roles/state_guard/tasks/pre_guard.yml"
  vars:
    component: "{{ component_name }}"
    asset_type: "{{ asset_type }}"
    current_state: "{{ component_state }}"
    target_state: "{{ actual_target_state }}"
    component_dependencies: "{{ asset_definitions[component_name].dependencies | default([]) }}"
  when: 
    - target_state is defined
    - target_state != ""
    - component_state is defined
    - not (skip_guard | default(false))
    - not (asset_type_info.disable_pre_state_guard | default(false))
  tags:
    - pre_state_guard
    - transition_validation

# State Persist - Set transient state BEFORE operations (SCOPED)
- name: "State Change: State Persist - Set transient state before operations"
  ansible.builtin.include_role:
    name: state_persist
  vars:
    component: "{{ component_name }}"
    asset_type: "{{ asset_type }}"
    new_state: "{{ transient_state }}"
  when: 
    - target_state is defined
    - target_state != ""
    - transient_state != ""
    - not skip_transient_mapping
  tags:
    - state_persist
    - transient_state_set

# Dynamic transition execution based on component type
- name: "State Change: Execute transition actions for component"
  ansible.builtin.include_role:
    name: "{{ transition_role_full_name }}"
  vars:
    target_state: "{{ actual_target_state }}"
    current_state: "{{ component_state }}"
    component_instance: "{{ component_name }}"
    asset_type_info: "{{ asset_type_info }}"
    role_timeout: "{{ transition_role_timeout }}"
    component_dependencies: "{{ asset_definitions[component_name].dependencies | default([]) }}"
    transient_state: "{{ transient_state }}"
    transient_success_state: "{{ transient_success_state }}"
    transient_failure_state: "{{ transient_failure_state }}"
    transient_timeout: "{{ transient_timeout }}"
  when: 
    - component_state is defined
    - target_state is defined
    - target_state != ""
    - not dry_run
    - not skip_transient_mapping
  tags:
    - transition_execution
    - "execute_actions_{{ component_name }}"

- name: "State Change: Skip transition - already in target state"
  ansible.builtin.debug:
    msg: "Skipping transition for {{ component_name }} - already in target state {{ target_state }}"
  when: 
    - component_state is defined
    - target_state is defined
    - target_state != ""
    - skip_transient_mapping
  tags:
    - transition_execution
    - skip_transition

# State Persist - Complete transition to final state (SCOPED)
- name: "State Change: State Persist - Complete transition to final state"
  ansible.builtin.include_role:
    name: state_persist
  vars:
    component: "{{ component_name }}"
    asset_type: "{{ asset_type }}"
    new_state: "{{ target_state }}"
  when: 
    - target_state is defined
    - target_state != ""
    - transient_state != ""
    - not skip_transient_mapping
  tags:
    - state_persist
    - final_state_completion

# State Persist - Persist non-transient states directly (SCOPED)
- name: "State Change: State Persist - Persist non-transient state"
  ansible.builtin.include_role:
    name: state_persist
  vars:
    component: "{{ component_name }}"
    asset_type: "{{ asset_type }}"
    new_state: "{{ target_state }}"
  when: 
    - target_state is defined
    - target_state != ""
    - transient_state == ""
    - skip_transient_mapping
  tags:
    - state_persist
    - state_persistence

# POST State Guard - Final state validation after asset transition
- name: "State Change: POST State Guard - Skip POST guard validation for configured asset types"
  ansible.builtin.debug:
    msg: "POST State guard validation skipped for {{ component_name }} (asset_type={{ asset_type }}, disable_post_state_guard=true)"
  when: 
    - target_state is defined
    - target_state != ""
    - component_state is defined
    - asset_type_info.disable_post_state_guard | default(false)
  tags:
    - post_state_guard
    - transition_validation

- name: "State Change: POST State Guard - Validate final state"
  ansible.builtin.include_tasks: "{{ playbook_dir }}/roles/state_guard/tasks/post_guard.yml"
  vars:
    component: "{{ component_name }}"
    asset_type: "{{ asset_type }}"
    current_state: "{{ component_state }}"
    target_state: "{{ original_target_state }}"
    component_dependencies: "{{ asset_definitions[component_name].dependencies | default([]) }}"
  when: 
    - original_target_state is defined
    - original_target_state != ""
    - component_state is defined
    - not (skip_guard | default(false))
    - not (asset_type_info.disable_post_state_guard | default(false))
  tags:
    - post_state_guard
    - transition_validation

- name: "State Change: Post-Task - Display final state information"
  ansible.builtin.debug:
    msg:
      - "Component: {{ component_name }}"
      - "Final State: {{ component_state | default('unknown') }}"
      - "Target State: {{ target_state | default('none') }}"
      - "Execution Status: {{ 'completed' if not dry_run else 'dry-run' }}"

- name: "State Change: Post-Task - Display state fact file location"
  ansible.builtin.debug:
    msg: "State fact file: {{ state_machine_config.fact_file_path | default('/etc/ansible/facts.d/state_' + component_name + '.fact') }}"
  when: not dry_run

# State Change: Set component state in global map with FINAL state values
- name: "State Change: Get current timestamp"
  ansible.builtin.command: date -u +"%Y-%m-%dT%H:%M:%SZ"
  register: current_timestamp
  changed_when: false

- name: "State Change: Store FINAL component state in global map"
  ansible.builtin.set_fact:
    component_states: "{{ component_states | default({}) | combine({component_name: {
      'state': target_state,
      'timestamp': current_timestamp.stdout,
      'method': 'state_change',
      'valid': true
    }}) }}"
  tags:
    - state_context
    - state_reading
    - component_states_map
    - final_state
