---
- name: Check parameters
  ansible.builtin.validate_argument_spec:
    argument_spec:
      os_stop_asset_id:
        type: str
        required: true
        description: "ID of the asset to stop"

- name: "OS Stop role executed"
  ansible.builtin.debug:
    msg: "Hello from OS Stop procedure"

- name: "Assert OS state"
  ansible.builtin.include_role:
    name: toolchain.fsm.state_assert
  vars:
    state_assert_asset_id: "{{ os_stop_asset_id }}"
    state_assert_expected_state: "STOPPING"

- name: "OS Stop: pause for 5 seconds"
  ansible.builtin.pause:
    seconds: 5
