---
# Metadata for transition_app_instance role
galaxy_info:
  role_name: transition_app_instance
  author: Component Owner
  description: "Transition logic for application instances in state-driven playbook framework"
  company: "Component Team"
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: CentOS
      versions:
        - 7
        - 8
    - name: RHEL
      versions:
        - 7
        - 8
        - 9
    - name: macOS
      versions:
        - 10.15
        - 11.0
        - 12.0
  galaxy_tags:
    - app
    - transition
    - state_machine
    - platform

dependencies: []
