---
# Default variables for state_persist role

# Component name - should be overridden when using the role
L2_component: "{{ component_name | default('resource') }}"

# State machine data - get from asset's state_machine_spec
L2_state_machine_data: "{{ state_machines[asset_definitions[L2_component_name].state_machine_spec] }}"

# New state to persist - should be provided when using the role
L2_new_state: "{{ target_transition | default('') }}"

# Fact file path for state persistence
L2_state_fact_file: "./state/state_{{ L2_component }}.fact"

# Backup settings
L2_backup_enabled: true
L2_backup_directory: "./state/backups"
L2_backup_retention_days: 30

# Persistence settings
L2_persistence_settings:
  create_backup: true
  validate_state: true
  update_timestamp: true
  include_metadata: true

# Metadata to include in fact file
L2_metadata_fields:
  - "ansible_hostname"
  - "ansible_date_time.iso8601"
  - "ansible_user_id"
  - "ansible_play_name"
