---
# Main tasks for L2_state_transient role
# This role handles automatic transient state management with L2 namespace protection

- name: "L2 State Transient - Validate required variables"
  assert:
    that:
      - component is defined and component != ""
      - target_state is defined and target_state != ""
      - current_state is defined and current_state != ""
    fail_msg: "Missing required variables: component='{{ component }}', target_state='{{ target_state }}', current_state='{{ current_state }}'"
    success_msg: "All required variables are present"
  tags:
    - L2_state_transient
    - L2_transient_handling

- name: "L2 State Transient - Initialize transient state handling for {{ component }}"
  set_fact:
    L2_transient_handling_timestamp: "{{ ansible_date_time.iso8601 }}"
    L2_transient_handling_success: false
    L2_actual_target_state: "{{ target_state }}"
    L2_transient_state: ""
  tags:
    - L2_state_transient
    - L2_transient_handling

- name: "L2 State Transient - Check if target state has transient mapping"
  set_fact:
    L2_has_transient_mapping: "{{ target_state in component_state_machine.transient_mappings }}"
    L2_transient_mapping: "{{ component_state_machine.transient_mappings[target_state] | default({}) }}"
  tags:
    - L2_state_transient
    - L2_transient_handling

- name: "L2 State Transient - Check if current state is already a transient state"
  set_fact:
    L2_current_is_transient: "{{ current_state in ['STARTING', 'STOPPING', 'TERMINATING'] }}"
  tags:
    - L2_state_transient
    - L2_transient_handling

- name: "L2 State Transient - Handle transition from transient state to different final state"
  set_fact:
    L2_actual_target_state: "{{ target_state }}"
    L2_transient_state: ""
    L2_transient_success_state: ""
    L2_transient_failure_state: ""
    L2_transient_timeout: ""
    L2_skip_transient_mapping: false
  when: 
    - L2_current_is_transient
    - target_state != current_state
  tags:
    - L2_state_transient
    - L2_transient_handling

- name: "L2 State Transient - Check if already in target final state"
  set_fact:
    L2_already_in_target_state: "{{ current_state == target_state }}"
  tags:
    - L2_state_transient
    - L2_transient_handling

- name: "L2 State Transient - Handle case where already in target state"
  set_fact:
    L2_actual_target_state: "{{ target_state }}"
    L2_transient_state: ""
    L2_transient_success_state: ""
    L2_transient_failure_state: ""
    L2_transient_timeout: ""
    L2_skip_transient_mapping: true
  when: 
    - L2_has_transient_mapping
    - not (L2_skip_transient_mapping | default(false))
    - L2_already_in_target_state
  tags:
    - L2_state_transient
    - L2_transient_handling

- name: "L2 State Transient - Set transient state if mapping exists and not skipping"
  set_fact:
    L2_actual_target_state: "{{ L2_transient_mapping.transient_state }}"
    L2_transient_state: "{{ L2_transient_mapping.transient_state }}"
    L2_transient_success_state: "{{ L2_transient_mapping.success_state }}"
    L2_transient_failure_state: "{{ L2_transient_mapping.failure_state }}"
    L2_transient_timeout: "{{ L2_transient_mapping.timeout | default(300) }}"
    L2_skip_transient_mapping: false
  when: 
    - L2_has_transient_mapping
    - not (L2_skip_transient_mapping | default(false))
    - not L2_already_in_target_state
  tags:
    - L2_state_transient
    - L2_transient_handling

- name: "L2 State Transient - Handle case where no transient mapping needed"
  set_fact:
    L2_actual_target_state: "{{ target_state }}"
    L2_transient_state: ""
    L2_transient_success_state: ""
    L2_transient_failure_state: ""
    L2_transient_timeout: ""
    L2_skip_transient_mapping: false
  when: 
    - not L2_has_transient_mapping
    - not (L2_skip_transient_mapping | default(false))
  tags:
    - L2_state_transient
    - L2_transient_handling

- name: "L2 State Transient - Display transient handling decision"
  debug:
    msg:
      - "Component: {{ component }}"
      - "Current State: {{ current_state }}"
      - "Original Target: {{ target_state }}"
      - "Actual Target: {{ L2_actual_target_state }}"
      - "Current is Transient: {{ L2_current_is_transient }}"
      - "Skip Transient Mapping: {{ L2_skip_transient_mapping | default(false) }}"
      - "Transient State: {{ L2_transient_state | default('none') }}"
      - "Success State: {{ L2_transient_success_state | default('none') }}"
      - "Failure State: {{ L2_transient_failure_state | default('none') }}"
      - "Timeout: {{ L2_transient_timeout | default('none') }} seconds"
      - "Has Transient Mapping: {{ L2_has_transient_mapping }}"
      - "Already in Target State: {{ L2_already_in_target_state }}"
  tags:
    - L2_state_transient
    - L2_transient_info

- name: "L2 State Transient - Set transient handling success"
  set_fact:
    L2_transient_handling_success: true
  tags:
    - L2_state_transient
    - L2_transient_handling

- name: "L2 State Transient - Display transient handling result"
  debug:
    msg:
      - "Component: {{ component }}"
      - "Transient Handling: {{ 'enabled' if L2_transient_state != '' else 'disabled' }}"
      - "Final Target State: {{ L2_actual_target_state }}"
      - "Handling Success: {{ L2_transient_handling_success }}"
  tags:
    - L2_state_transient
    - L2_transient_info
