---
# Stop services for service transition
# This task handles service shutdown logic for service instances

- name: "Stop Services - Check if services need to be stopped"
  set_fact:
    should_stop_services: "{{ target_state in ['STOPPING', 'STOPPED', 'TERMINATING', 'TERMINATED'] and component_services | default([]) | length > 0 }}"

- name: "Stop Services - Display service shutdown information"
  debug:
    msg:
      - "Target State: {{ target_state }}"
      - "Should Stop Services: {{ should_stop_services }}"
      - "Services to Stop: {{ component_services | default([]) | join(', ') }}"
  when: should_stop_services

- name: "Stop Services - Stop system services gracefully"
  systemd:
    name: "{{ item }}"
    state: stopped
  loop: "{{ component_services | default([]) }}"
  when: should_stop_services
  register: service_stop_result

- name: "Stop Services - Wait for services to stop"
  wait_for:
    port: "{{ item }}"
    state: stopped
    timeout: 30
    delay: 2
  loop: "{{ component_ports | default([]) }}"
  when: 
    - should_stop_services
    - component_ports | default([]) | length > 0

- name: "Stop Services - Force stop services if graceful stop failed"
  systemd:
    name: "{{ item }}"
    state: stopped
  loop: "{{ component_services | default([]) }}"
  when: 
    - should_stop_services
    - service_stop_result is defined
    - service_stop_result.results | selectattr('failed', 'equalto', true) | list | length > 0
  register: force_stop_result

- name: "Stop Services - Verify services are stopped"
  systemd:
    name: "{{ item }}"
  loop: "{{ component_services | default([]) }}"
  register: service_status_result
  when: should_stop_services

- name: "Stop Services - Check for services that failed to stop"
  fail:
    msg: "Failed to stop services: {{ service_status_result.results | selectattr('status.ActiveState', 'in', ['active', 'activating']) | map(attribute='item') | list | join(', ') }}"
  when: 
    - should_stop_services
    - service_status_result.results | selectattr('status.ActiveState', 'in', ['active', 'activating']) | list | length > 0

- name: "Stop Services - Record successful service shutdown"
  set_fact:
    transition_actions_executed: "{{ transition_actions_executed | default([]) + ['services_stopped'] }}"
  when: should_stop_services
