---
galaxy_info:
  role_name: app_stop
  author: App Team
  description: Role for stopping App1 application
  company: App Team
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: CentOS
      versions:
        - 7
        - 8
  galaxy_tags:
    - app1
    - stop
    - application
