---
# Stop services for app instance transition
# This task handles service shutdown logic for application instances

- name: "Stop App - Check if app need to be stopped"
  set_fact:
    should_stop_app: "{{ target_state in ['STOPPING', 'STOPPED', 'TERMINATING', 'TERMINATED'] and component_services | default([]) | length > 0 }}"

- name: "Stop App - Display app shutdown information"
  debug:
    msg:
      - "Target State: {{ target_state }}"
      - "Should Stop App: {{ should_stop_app }}"
      - "App to Stop: {{ component_services | default([]) | join(', ') }}"
  when: should_stop_app


- block:
    - name: "Stop App - Pause for 3 seconds"
      pause:
        seconds: 3

    - name: "Stop App - Record successful shutdown"
      set_fact:
        transition_actions_executed: true"
  when: should_stop_app

