---
# Set final state facts from map
# This task sets the final state facts based on the component data from the map

- name: "Map State - Set final state facts from map"
  set_fact:
    component_state: "{{ current_state }}"
    component_state_timestamp: "{{ state_reading_timestamp }}"
    component_state_method: "{{ state_reading_method }}"
    component_state_valid: "{{ current_component_data.valid | default(true) }}"
    component_state_previous: "{{ current_component_data.previous_state | default('') }}"
    component_state_transition: "{{ current_component_data.transition | default('') }}"
    component_state_metadata: "{{ current_component_data.metadata | default({}) }}"
