---
namespace: platformteam
name: transition
version: 1.0.0
readme: README.md
authors:
  - Platform Team
description: Platform team transition roles for state-driven playbook framework
license_file: LICENSE
tags:
  - platform
  - transition
  - state_machine
dependencies: {}
