---
galaxy_info:
  role_name: os_stop
  author: Platform Team
  description: Simple role for stopping Linux services
  company: Platform Team
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: CentOS
      versions:
        - 7
        - 8
  galaxy_tags:
    - linux
    - stop
    - services
