---
galaxy_info:
  role_name: service_stop
  author: Service Team
  description: Role for stopping Service1 service
  company: Service Team
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: CentOS
      versions:
        - 7
        - 8
  galaxy_tags:
    - service1
    - stop
    - service
