- name: Request node stop
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Change state node1 to STOPPING
      ansible.builtin.include_role:
        name: toolchain.fsm.transition
      vars:
        transition_asset_id: "node1"
        transition_to_state: "STOPPING"
