---
# Default variables for state_persist role

# Component name - should be overridden when using the role
component: "{{ component_name | default('resource') }}"

# State machine configuration
state_machine_config: "{{ state_machine }}"

# New state to persist - should be provided when using the role
new_state: "{{ target_transition | default('') }}"

# Fact file path for state persistence
state_fact_file: "{{ state_machine_config.fact_file_path | default('/etc/ansible/facts.d/state_' + component + '.fact') }}"

# Backup settings
backup_enabled: "{{ state_machine_config.backup_enabled | default(true) }}"
backup_directory: "/etc/ansible/facts.d/backups"
backup_retention_days: 30

# Persistence settings
persistence_settings:
  create_backup: true
  validate_state: true
  update_timestamp: true
  include_metadata: true

# Metadata to include in fact file
metadata_fields:
  - "ansible_hostname"
  - "ansible_date_time.iso8601"
  - "ansible_user_id"
  - "ansible_play_name"
