---
namespace: appteam
name: app1
version: 1.0.0
readme: README.md
authors:
  - App Team
description: Collection for managing the App1 application
license_file: LICENSE
dependencies: {}
repository: https://github.com/appteam/app1
