namespace: appteam
name: app1
version: 1.0.0
readme: README.md
authors:
  - App Team
description: App1 application management collection
license_file: LICENSE
tags:
  - app1
  - application
  - management
dependencies: {}
